apiVersion: v1
kind: Service # Type of the kubernetes resource
metadata:
  name: go-blog-api-mysql # Name of the Kubernetes resource
  labels: # Labels that will be applied to the resource
    app: go-blog-api-mysql
spec:
  type: NodePort # Gives each node an external IP that’s accessible from outside the cluster and also opens a Port.
  selector:
    app: go-blog-api-mysql # Selects any Pod with labels `app=go-blog-api-mysql`
  ports:
    - name: http
      port: 8080
      targetPort: 8080
