apiVersion: v1 # API version
kind: Service # Type of kubernetes resource
metadata:
  name: go-blog-mysql # Name of the resource
  labels: # Labels that will be applied to the resource
    app: go-blog-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
  selector: # Selects any Pod with labels `app=go-blog-mysql, tier=mysql`
    app: go-blog-mysql
    tier: mysql
